### ISSUE TITLE
WR times should be optional

### ISSUE THREAD

**Issue by SmurfySR** [xTVaser/src-twitch-ext#23]
A lot of speedrunners arent going for wr, and therefore displaying the wr times isnt necessary

**Comment by xTVaser** [comment]
I'll look into adding this for the next release, it shouldnt be too difficult to add.  Also the twitch approval / testing process is quite annoying so I like to have a few things to do for each release but if nothing else comes up in the next week or so then ill make a release for just this issue.

I understand that a lot of speedrunners aren't going for WR.  But I see it as just providing information on the category as people are always asking what the WR times are.

Still, if its something that you want perhaps there are others in the same boat.
