### ISSUE TITLE
Import / Export Settings

### ISSUE THREAD

**Issue by xTVaser** [xTVaser/src-twitch-ext#28]
This will allow people to have a local backup, and it opens the door for presets of settings rather than custom CSS

**Comment by AlphaKR** [comment]
would it be possible to have a reset settings button so all the enhancements made can be reset to the default
![image](https://user-images.githubusercontent.com/33771552/32976889-5f29b054-cbef-11e7-81a8-4c51130f4b05.png)
such as these settings ^

**Comment by xTVaser** [comment]
Yup, rather than having a reset settings button, there can just be a default preset, among a few others (for example settings that look ok with a light-themed twitch / a dark themed twitch, etc.
