### ISSUE TITLE
Order of categories

### ISSUE THREAD

**Issue by OoDeeR** [xTVaser/src-twitch-ext#32]
**This is a...**  

- [] Bug Report  
- [X] Feature Request

## Brief Description

Custom order of categories / order presets

## (If Bug Report) Steps to Reproduce
Speedrun.com Name - `<name here>`  
Twitch.tv Profile Link - `[Twitch Profile Link](wwww.linkgoeshere.com)` 

List Steps:
1. Enter name
2. Click "Save"
3. Nothing happens, fix it!

## (If Feature Request) Describe it. 

I may be missing something, but currently categories seem to be ordered strictly alphabetically. It would be very useful to be able to sort them manually or maybe have presets (alphabetically, based on number of submissions on srdotcom, custom, ?)

P.S.: Thanks for providing this extension! :-)

**Comment by xTVaser** [comment]
Yup I agree and others have suggested it. Currently working on it in #26 it requires a pretty big redesign of the config page so its more tricky than I expected but its the last difficult thing I have to do before the next version, so hopefully before the end of the month.
