### ISSUE TITLE
Unable to customize dividers

### ISSUE THREAD

**Issue by AshMarks** [xTVaser/src-twitch-ext#63]
**This is a...**  

- [x] Bug Report  
- [ ] Feature Request

## Description

Trying to customize either the Panel Title Divider, or the Game Divider results in no change at all.

## Steps to Reproduce
Speedrun.com Name - [Ash_Marks](http://www.speedrun.com/user/Ash_Marks)  
Twitch.tv Profile Link - [Ash_Marks](https://www.twitch.tv/ash_marks)  

Steps:
1. Customize Panel Title/Game Divider Settings
2. Click "Save"
3. No changes occur

**Comment by xTVaser** [comment]
Good catch, can now properly change the dividers, should be up on Twitch within 2-3 days (whenever they review it)
