### ISSUE TITLE
Export Style Settings unchanged .json file

### ISSUE THREAD

**Issue by AshMarks** [xTVaser/src-twitch-ext#64]
**This is a...**  

- [X] Bug Report  
- [ ] Feature Request

## Brief Description

Export Style Settings exports the default settings, not my customized settings.

## Steps to Reproduce
Speedrun.com Name - [Ash_Marks](http://www.speedrun.com/user/Ash_Marks)  
Twitch.tv Profile Link - [Ash_Marks](https://www.twitch.tv/ash_marks)  

Steps:
1. Customize the panel
2. Click "Save"
3. Click "Export Style Settings"
4. Download the .json file
5. It's default, not changed at all

**Comment by xTVaser** [comment]
Not relevant anymore with the release of v2, there is no export/import feature because there are far less configuration options in favor of just doing things automatically.
