### ISSUE TITLE
WR time compares to wrong subcategory

### ISSUE THREAD

**Issue by Henny022** [xTVaser/src-twitch-ext#67]
**This is a...**  

- [X] Bug Report  
- [ ] Feature Request

## Brief Description

The panel compares my NG PB to the NG+ WR

## (If Bug Report) Steps to Reproduce
Speedrun.com Name - `henny022`  
Twitch.tv Profile Link - `[Twitch Profile Link](https://www.twitch.tv/henny022)` 

List Steps:
1. look at PB's category -> NG
2. look at WR category -> NG+

**Comment by Tamijo-Netrunner** [comment]
Also have this issue. On Hyper Light Drifter boards my Any% NMG New Game time is comparing to Alt Drifter time. 

Image of top of Leaderboard I am on: (Though much further down)
![image](https://user-images.githubusercontent.com/39098450/105978109-12143680-608a-11eb-85ad-d74a651adce2.png)

Image of Leaderboard it is comparing to: 
![image](https://user-images.githubusercontent.com/39098450/105978193-2d7f4180-608a-11eb-89ed-2d3ccf7d07db.png)

Image of my Extension:
![image](https://user-images.githubusercontent.com/39098450/105978243-3bcd5d80-608a-11eb-865c-2896dd2d5735.png)

For reference Hollow Knight is comparing correctly.

Speedrun.com name: TamiJo
Twitch account: Twitch.tv/tamijostreams

**Comment by xTVaser** [comment]
Separate WR column was removed in v2 for added horizontal space for the category name.
