### ISSUE TITLE
"Find games" removes order/settings of old games

### ISSUE THREAD

**Issue by OCircles** [xTVaser/src-twitch-ext#71]
**This is a...**  

- [ ] Bug Report  
- [X] Feature Request

## Brief Description

What it says in the title. This makes it so whenever you started running a new game and want it added to the list, you have to manually write down your current game order and then input the settings for each individual one manually. Very tedious.

## (If Feature Request) Describe it. 

Make it append new stuff to old stuff instead of just replacing everything. Either that, or make an export/import system like you have with themes

**Comment by xTVaser** [comment]
This is fixed in v2, and you no longer have to refresh your game list unless you want to disable new games.
