### ISSUE TITLE
Saving Error: Database Error

### ISSUE THREAD

**Issue by CptBrian** [xTVaser/src-twitch-ext#74]
- [X] Bug Report  

## Brief Description

Cannot save no matter what I do, and as a result the panel never loads.

## Steps to Reproduce
Speedrun.com Name - `CptBrian`  
Twitch.tv Profile Link - https://www.twitch.tv/CptBrian

1. Enter name
2. Find games
3. Click "Save" with any settings

**Comment by CptBrian** [comment]
It appears the dev's been MIA for 3 years...
Really hoping somebody can maintain this extension, because all other options are still significantly worse.

**Comment by xTVaser** [comment]
I'm looking into the current issue, apologies, im aware of many bugs but saving/loading should function atleast for now.

I've wanted to get back into working on the extension for quite a while (as you said 3 years) but I've had a lot of competing priorities, I should be able to get back into it very soon though.  TBH, I personally would be going for the direction of starting almost from scratch as this was originally very rushed, unfortunate that nothing better has come along, but I guess that still leaves me with room to improve it despite all the time that has gone by.

**Comment by xTVaser** [comment]
Issue should be resolved, let me know if problems persist, I'll leave the issue opened until you confirm.

As I said above, hopefully I can get started soon on giving the extension a major overhaul / fixing some of the now-longstanding issues.  Thanks for reporting a problem -- for context it was some underlying authentication issue with Google Cloud (couldn't load/save anything in the database)

**Comment by CptBrian** [comment]
It's fixed now, thanks, and sorry for the late reply.
