### ISSUE TITLE
Individual Levels with Categories do not display each properly as their own entry

### ISSUE THREAD

**Issue by KeithDeRuiter** [xTVaser/src-twitch-ext#76]
**This is a...**  
- [x] Bug Report  
- [ ] Feature Request

## Brief Description
Individual Levels do not account for level Categories (e.g. an Easy vs. Hard mode for the same level).  They all just display as one row in the extension when they should each display as their own submission/row.

## Steps to Reproduce
Speedrun.com Name - [`AlteranQuidem`](https://www.speedrun.com/user/AlteranQuidem)
Twitch.tv Profile Link - [`AlteranQuidem`](https://www.twitch.tv/alteranquidem)

List Steps:
Prerequisites- A game with Individual Levels that have multiple Categories (I noticed with Blasphemous)

1. Submit (or have) a run for multiple categories of the same level.
![image](https://user-images.githubusercontent.com/1069615/129801749-91a1fdde-d7d5-4c70-9e94-def55e7691a6.png)

2. Configure the extension to show that game and individual levels (Screenshot shows only one submission for "First XYZ..." in the "Pilgrim" category, ignore the "Second XYZ..." entry).
![image](https://user-images.githubusercontent.com/1069615/129801841-59539cb9-ebb9-4d0a-b052-fa67abbed4e1.png)

3. Observe that the Submission for the "True Torment" category of that First level is not present.

The JSON for the game's list of levels shows one entry for each of the different levels (in this game that's 5 levels)
https://www.speedrun.com/api/v1/games/lde39mx6/levels

But the missing information is at data.links.categories which brings you to this response:
https://www.speedrun.com/api/v1/levels/ywex57l9/categories

That payload does list the two separate categories which each have their own ID.  If a level has categories, then those should be iterated through to grab runs and display separately vs. just lumping everything together in one category.

**Comment by xTVaser** [comment]
V2 fixes this:
![image](https://github.com/xTVaser/src-twitch-ext/assets/13153231/f74af652-1910-45dd-b90d-cb673976e4d1)
