### ISSUE TITLE
Pulled or malfunctioning?

### ISSUE THREAD

**Issue by jasperfrontend** [xTVaser/src-twitch-ext#78]
It seems this extension is no longer functioning. Screenshots don't load in on the [Extension Page](https://dashboard.twitch.tv/extensions/u2nvainvlx73h5a7cnxpiodpfcbmo1) either. When we try to enable the extension, it gives auth errors and that's it. 

Will it come back?

**Comment by jasperfrontend** [comment]
Ok pulled :)

**Comment by xTVaser** [comment]
Apologies for the late reply.

It was not pulled, there were two issues.  
- There is a looming deprecation for Twitch's V5 API which is slated for the end of the this month.  This was well communicated and I was aware of it for some time.
- However there was another quick change to the extensions CSP policies that went in effect at the end of January - https://discuss.dev.twitch.tv/t/new-extensions-policy-for-content-security-policy-csp-directives-and-timeline-for-enforcement/33695
  - This is the reason everything broke and I don't seem to be the only one that was caught off-guard.

I put in a release today for approval that fixes both of these issues.

In general though, this extension needs a re-write badly -- which should make things a lot more stable in the long run....
