### ISSUE TITLE
Broken.

### ISSUE THREAD

**Issue by BrynnaDaRosa** [xTVaser/src-twitch-ext#80]
**This is a...**  

- [X] Bug Report  
- [ ] Feature Request

I was sure somebody would have reported already but for the past several days every speedrunner i've watched on twitch who has this extension, the extension has broken.

I assume it just can't communicate with SR.com anymore. or at least for the most part. I actually added the extension myself and tried to set it up for the first time and i put my name in, it kept saying i hadn't put a name in at all, not sure what i did, but i suddenly got it to respond a little and it detected the one game i had runs in, and i was able to select categories to include, but saving it only brings up the notice **ERROR: An Unexpected Error Occurred, Contact Extension Developer**. So, that's what I'm doing.

**Comment by metalmachine76** [comment]
Looks like https://extension.xtvaser.xyz is down (returns a 521 error). It's something that whoever runs that webserver needs to fix ( I'm assuming it's @xTVaser ). But seeing as they haven't been active in 5 years, it seems unlikely this will be addressed any time soon.
