### ISSUE TITLE
runs appearing 3 times

### ISSUE THREAD

**Issue by supermeatboy10** [xTVaser/src-twitch-ext#82]
When I expand a game to show the runs it shows every category 3 times. This happens on every game, not just one. I have attached an example 

![image](https://user-images.githubusercontent.com/87836604/212393658-46516a8a-80a2-4505-bf69-ccc8b5d10ffb.png)

**Comment by xTVaser** [comment]
Fixed in v2 
![image](https://github.com/xTVaser/src-twitch-ext/assets/13153231/a2e5059b-a425-4979-9061-6c8c0c7aa5e7)
