### ISSUE TITLE
PB WR runs do not visually pop out compared to other runs

### ISSUE THREAD

**Issue by binaryribbit** [xTVaser/src-twitch-ext#86]
I know that WR runs in general are a different color at the moment but there is no visual way to see if my PB is the WR.
At the moment you have to either look if the run url is the same or look at the time and hope two people do not have the same time.

It would be nice if the PB WR runs could visually be different somehow to show that my PB is also the current WR.

**Comment by xTVaser** [comment]
With the release of v2 (just went live on twitch today):
- you can make your run have a rainbow effect if it's a world record
- you can enable an explicit leaderboard place number next to your runs

https://github.com/xTVaser/src-twitch-ext/issues/65
